projects:
  testpoems:
    schemaPath: src/graphql/schema.json
    includes:
      - operations
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
